export function packageJsonTemplate() {
  return JSON.stringify(
    {
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "16.1.1",
        react: "19.2.3",
        "react-dom": "19.2.3",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        typescript: "^5",
      },
    },
    null,
    2,
  );
}

export function pageTemplate(componentBody: string) {
  return `export default function Page() {
  return (
${componentBody
  .split("\n")
  .map((line) => `    ${line}`)
  .join("\n")}
  );
}
`;
}

export function layoutTemplate() {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "VNBuilder Export",
  description: "Generated by VNBuilder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

export function globalsCssTemplate() {
  return `* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  min-height: 100%;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

.vn-page {
  min-height: 100vh;
}

.vn-container,
.vn-section,
.vn-header,
.vn-footer {
  width: 100%;
}

.vn-flex {
  display: flex;
}

.vn-grid {
  display: grid;
}

.vn-image {
  max-width: 100%;
}
`;
}

export function nextConfigTemplate() {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
}

export function tsconfigTemplate() {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  );
}

export function readmeTemplate() {
  return `# VNBuilder Export

This project was generated by VNBuilder.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
`;
}
